### ISSUE TITLE
Wrong names of nations

### ISSUE THREAD

**Issue by 5rdx** [darthpeti/TownyTweaks#6]
In webhooks the defender nation's name gets to attacker nation's name, please fix this.

**Comment by Gl0W1E** [comment]
Hello! I'll be able to fix this in a few hours. You should see a new release then.
Thanks for reporting it!

**Comment by Gl0W1E** [comment]
Which webhook is it? The siege start?

**Comment by Gl0W1E** [comment]
This shouldn't have happened. Can you let me know if it still happens with the updated version?
https://github.com/Gl0W1E/TownyTweaks/releases/tag/v0.1.4 here is the new version.

**Comment by 5rdx** [comment]
Yeah, it looks fixed. By the way it would be great if the siege start webhook sends the attacker nation name instead of attacker capital. Maybe you could add this in config but i would definitely choose the sending attacker nation name.

**Comment by Gl0W1E** [comment]
I'll do this next update, when I also add more cool stuff. Thanks!
